name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Copy repository contents to remote server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "."
          target: "${{ secrets.TARGET }}-build-testing-non/"

      - name: Executing server and client build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{secrets.TARGET}}-build-testing-non/
            printf "%s" "${{secrets.PROD_ENV}}" > "${{secrets.TARGET}}/.env"
            npm run build:client
            npm run build:server

      - name: Build sucessfull / Best lap time 
        run: |
          echo "                                 *(###*#%%%##/"
          echo "                            (/#(#((/%#(((/(%&&&/%/."
          echo "                         *#/*#%%%%#(#/((#%&@&%#%(%##,"
          echo "                      .#(/(&&%%(#%&@%@%@@@&&&@&&#(&%#//"
          echo "                     /**&&&@&&/#%%#@%@&&&&&&&&&&%%#%%%#("
          echo "                    **(/#&&&&&&&&%%%%#%%##/////(#((#%&%#%"
          echo "                    *(%##/(/*****/*****,,,,.,,,,**(%%&##*"
          echo "                   (/#&##*.,,,,,,.........,,,,,,,,/#%%(#,"
          echo "                   *((*(,,..,,,,,,,,,,,,,,,******,,.,%#*"
          echo "                    /((* .,(%#&&&&%(/*,*(%%&%%##%%(..(/.,"
          echo "                    ***/../*&#&@%%%%#,,,/%%&/%&%&%(*../*(,("
          echo "                   (,**,..,,***//,,*,.,,*/*,,*((*,,,,..*/,*"
          echo "                   ,,*,....,,,..,,,*,,,.*,/*,,,,,,*,...,#(*"
          echo "                   ,**.....,,,,,,,,/*(/((@%*,*,****,,..*,,*"
          echo "                    *./*.,,****,,**,/#%&%#/*,,,,*//*,.,**,"
          echo "                      ,*,.,*,,,,****////*/((///*.,**,."
          echo "                         ,,**,,*(#(*/*///(#(/******,*. "
          echo "                          ,,*///,,**(#%###////(***,,*"
          echo "                          .*,*//****,,,,,*,******/**."
          echo "                         &,***///((((#(##(##(((///*, "
          echo "                        /&,,,/**/#%%%%&&%&%%(///((/.&"
          echo "                        %%.,,**/**(#%%%%%&%#(//#((,#&#"
          echo "                      #,#%%%,,**///(###((#####((((#&#/&%"
          echo "                /%%%%%%,, %%&&%#*/((###%%%###(/@@&%%(#&&%%%&%&&&%%%%"
          echo "     .%##/%&&@@@&%@@%%@%#%%%%&&&&&&@@@@@&@@&@&&&&&&&&%&@&%&&&&&&&@@@@@(*%%("

  unit-tests:
    runs-on: ubuntu-latest
    needs: build-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Building client
        run: npm run build:client
        
      - name: Building server
        run: npm run build:server

      - name: Run unit tests
        run: npm run test:unit
        
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Copy repository contents to remote server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "."
          target: "${{ secrets.TARGET }}-build-testing"

      - name: Executing server and client build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd "${{secrets.TARGET}}-build-testing"
            printf "%s" "${{secrets.DEV_ENV}}" > "${{secrets.TARGET}}-build-testing/server/.env"
            printf "%s" "${{secrets.DEV_ENV}}" > "${{secrets.TARGET}}-build-testing/.env"
            npm run build:client
            npm run build:server
            pm2 start            
            npm run test:e2e
            pm2 stop

  deploy:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Copy repository contents to remote server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "."
          target: "${{ secrets.TARGET }}"

      - name: Executing server and client build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{secrets.TARGET}}-build-testing/
            printf "%s" "${{secrets.DEV_ENV}}" > "${{secrets.TARGET}}-build-testing/.env"
            npm run build:client
            npm run build:server
            pm2 start
